// Native CLIP BPE tokenizer tests (SDXL CLIP-L / OpenCLIP-G).
//
// Two layers:
//   1. Checkpoint-free unit tests: the GPT-2 byte map and the CLIP word-split
//      emulation on literals.
//   2. Creator-parity gate: embedded fixtures generated by
//      tools/export_clip_tokenizer_fixtures.py from the reference sampler's
//      SDXL tokenizer pair. For every prompt it checks encode() against the
//      raw HF CLIPTokenizer ids, the 77-slot CLIP-L (pad = EOS) and CLIP-G
//      (pad = 0) chunking, and the first-chunk num_tokens.
// Layer 2 needs vocab.json + merges.txt in the directory given as argv[1]
// (perf/regress/fixtures/clip-tokenizer); when they are absent the test
// reports SKIP via exit code 77 (registered SKIP_RETURN_CODE).
//
// Pinned fixture files (sha256 of the creator's sd1_tokenizer pair; the
// gate refuses to claim parity against anything else):
//   vocab.json e089ad92ba36837a0d31433e555c8f45fe601ab5c221d4f607ded32d9f7a4349
//   merges.txt 9fd691f7c8039210e0fced15865466c65820d09b63988b0174bfe25de299051a

#include "dif/support/error.hpp"
#include "dif/support/sha256.hpp"
#include "dif/text/clip_bpe_tokenizer.hpp"

#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <iostream>
#include <set>
#include <sstream>
#include <string>
#include <vector>

#include "clip_tokenizer_fixtures.inc"

namespace {

int failures = 0;

void expect(bool condition, const std::string &message) {
  if (!condition) {
    ++failures;
    std::cerr << "FAIL: " << message << "\n";
  }
}

constexpr const char *kVocabSha =
    "e089ad92ba36837a0d31433e555c8f45fe601ab5c221d4f607ded32d9f7a4349";
constexpr const char *kMergesSha =
    "9fd691f7c8039210e0fced15865466c65820d09b63988b0174bfe25de299051a";

// Prompts whose reference ids the native tokenizer is KNOWN not to
// reproduce, each traced to an approximation the header documents. The
// gate pins the CURRENT native output for them, so a change in either
// direction is visible: fixing the approximation makes `current` fail and
// the entry must then be deleted, re-enabling the reference comparison.
struct KnownDivergence {
  const char *name;
  const char *why;
  const std::int32_t *current;
  std::size_t current_count;
};

// The greek_cyrillic_caps prompt ("Ωmega ΣΙΓΜΑ Привет МИР"): the reference
// lowercases all of Unicode before splitting; the native tokenizer (like
// the Mojo original) folds ASCII and Latin-1 only, so Greek/Cyrillic
// capitals keep their upper-case UTF-8 bytes and the BPE lands on different
// byte-level merges (29 ids vs the reference's 22).
constexpr std::int32_t kCurrentGreekCyrillicCaps[] = {
    49406, 138, 102, 9068, 138, 96,  138, 247, 138,   241, 138, 250, 138, 495,
    140,   253, 16370, 29503, 110, 22176, 141, 480, 140, 250, 140, 246, 140,
    510,   49407,
};

constexpr KnownDivergence kKnownDivergences[] = {
    {"greek_cyrillic_caps",
     "Unicode case folding beyond Latin-1 is not applied (documented "
     "approximation)",
     kCurrentGreekCyrillicCaps,
     sizeof(kCurrentGreekCyrillicCaps) / sizeof(kCurrentGreekCyrillicCaps[0])},
};

const KnownDivergence *find_known_divergence(const char *name) {
  for (const KnownDivergence &entry : kKnownDivergences)
    if (std::string(entry.name) == name)
      return &entry;
  return nullptr;
}

std::string join(const std::vector<std::string> &pieces) {
  std::string out;
  for (const std::string &piece : pieces) {
    out += '[';
    out += piece;
    out += ']';
  }
  return out;
}

void expect_pretokens(const std::string &text,
                      const std::vector<std::string> &want) {
  const auto got = dif::text::clip_pretokenize(text);
  expect(got == want, "pretokenize(\"" + text + "\") = " + join(got) +
                          ", want " + join(want));
}

void run_unit_tests() {
  using dif::text::clip_byte_to_unicode;
  // GPT-2 bytes_to_unicode: printable Latin-1 identity, the 68 other bytes
  // (0..32, 127..160, 173) take U+0100.. in ascending byte order.
  expect(clip_byte_to_unicode('a') == U'a', "byte map: 'a' -> 'a'");
  expect(clip_byte_to_unicode(0xA1) == 0xA1U, "byte map: 0xA1 identity");
  expect(clip_byte_to_unicode(0xFF) == 0xFFU, "byte map: 0xFF identity");
  expect(clip_byte_to_unicode(0x00) == 0x0100U, "byte map: 0x00 -> U+0100");
  expect(clip_byte_to_unicode(0x20) == 0x0120U,
         "byte map: space -> U+0120 (\"Ġ\")");
  expect(clip_byte_to_unicode(0x7F) == 0x0121U, "byte map: 0x7F -> U+0121");
  expect(clip_byte_to_unicode(0xA0) == 0x0142U, "byte map: 0xA0 -> U+0142");
  expect(clip_byte_to_unicode(0xAD) == 0x0143U, "byte map: 0xAD -> U+0143");
  {
    std::set<char32_t> seen;
    for (unsigned b = 0; b < 256U; ++b)
      seen.insert(clip_byte_to_unicode(static_cast<unsigned char>(b)));
    expect(seen.size() == 256U, "byte map is a bijection");
  }

  // whitespace_clean + lowercase + CLIP word-split regex on literals.
  expect_pretokens("", {});
  expect_pretokens("  \t a \n ", {"a"});
  expect_pretokens("Hello,   World!'s 33x",
                   {"hello", ",", "world", "!'", "s", "3", "3", "x"});
  expect_pretokens("don't I'LL we're they'd I'm you've it's",
                   {"don", "'t", "i", "'ll", "we", "'re", "they", "'d", "i",
                    "'m", "you", "'ve", "it", "'s"});
  expect_pretokens("'s'tis 'x", {"'s", "'t", "is", "'", "x"});
  expect_pretokens("café ÀÉ 東京タワー 😀😀 x",
                   {"café", "àé", "東京タワー", "😀😀", "x"});
  expect_pretokens("1024x1024", {"1", "0", "2", "4", "x", "1", "0", "2", "4"});
  // Unicode White_Space (U+00A0, U+3000) separates; U+200B (zero width
  // space) is not White_Space, so it forms a punctuation run of its own.
  expect_pretokens("a\u00A0b\u3000c\u200Bd", {"a", "b", "c", "\u200B", "d"});
}

std::string first_divergence(const std::vector<std::int32_t> &got,
                             const std::int32_t *want, std::size_t want_count) {
  std::size_t i = 0;
  while (i < got.size() && i < want_count && got[i] == want[i])
    ++i;
  std::ostringstream out;
  out << "got " << got.size() << " ids, want " << want_count
      << ", first divergence at " << i << " (got ";
  if (i < got.size())
    out << got[i];
  else
    out << "<end>";
  out << ", want ";
  if (i < want_count)
    out << want[i];
  else
    out << "<end>";
  out << ")";
  return out.str();
}

bool same_ids(const std::vector<std::int32_t> &got, const std::int32_t *want,
              std::size_t want_count) {
  if (got.size() != want_count)
    return false;
  for (std::size_t i = 0; i < want_count; ++i)
    if (got[i] != want[i])
      return false;
  return true;
}

std::vector<std::int32_t> to_i32(const std::vector<std::uint32_t> &ids) {
  return std::vector<std::int32_t>(ids.begin(), ids.end());
}

} // namespace

int main(int argc, char **argv) {
  run_unit_tests();

  const std::filesystem::path dir =
      argc > 1 ? std::filesystem::path(argv[1])
               : std::filesystem::path("perf/regress/fixtures/clip-tokenizer");
  const auto vocab_json = dir / "vocab.json";
  const auto merges_txt = dir / "merges.txt";
  if (!std::filesystem::exists(vocab_json) ||
      !std::filesystem::exists(merges_txt)) {
    if (failures != 0)
      return 1;
    std::cout << "SKIP: vocab.json / merges.txt not found under " << dir
              << "\n";
    return 77;
  }
  expect(dif::hex_digest(dif::sha256_file(vocab_json)) == kVocabSha,
         "vocab.json sha256 must be the pinned creator file");
  expect(dif::hex_digest(dif::sha256_file(merges_txt)) == kMergesSha,
         "merges.txt sha256 must be the pinned creator file");

  // Fail-closed loader: a file without the "#version" header is not a
  // merges list.
  {
    bool threw = false;
    try {
      dif::text::ClipBpeTokenizer::load(vocab_json, vocab_json);
    } catch (const dif::Error &) {
      threw = true;
    }
    expect(threw, "load rejects a merges file without the #version header");
  }

  const auto tokenizer =
      dif::text::ClipBpeTokenizer::load(vocab_json, merges_txt);
  expect(tokenizer.vocab_size() == 49408U, "CLIP vocab has 49408 entries");
  expect(static_cast<std::int32_t>(tokenizer.bos_id()) == clip_fixtures::kBosId,
         "BOS id");
  expect(static_cast<std::int32_t>(tokenizer.eos_id()) == clip_fixtures::kEosId,
         "EOS id");
  expect(static_cast<std::int32_t>(tokenizer.eos_id()) ==
             clip_fixtures::kClipLPadId,
         "CLIP-L pads with the EOS id");
  expect(static_cast<std::int32_t>(dif::text::kSdxlClipGPadToken) ==
             clip_fixtures::kClipGPadId,
         "CLIP-G pads with 0");

  std::size_t checked = 0;
  std::size_t divergences = 0;
  for (const auto &parity_case : clip_fixtures::kClipCases) {
    const std::string label = std::string("case '") + parity_case.name + "'";
    const auto raw = to_i32(tokenizer.encode(parity_case.utf8));
    const auto sdxl =
        dif::text::sdxl_prompt_tokens(tokenizer, parity_case.utf8);
    ++checked;

    if (const auto *known = find_known_divergence(parity_case.name)) {
      ++divergences;
      expect(!same_ids(raw, parity_case.raw, parity_case.raw_count),
             label + " is listed as a known divergence but now matches the "
                     "reference; delete its kKnownDivergences entry");
      expect(same_ids(raw, known->current, known->current_count),
             label + " (known divergence: " + known->why + ") current ids: " +
                 first_divergence(raw, known->current, known->current_count));
      // The packing contract is still exercised: the chunks must be the
      // native raw body laid out the reference way.
      expect(sdxl.l.ids.size() == clip_fixtures::kMaxLength &&
                 sdxl.g.ids.size() == clip_fixtures::kMaxLength,
             label + " known divergence packs into one chunk");
      continue;
    }

    expect(same_ids(raw, parity_case.raw, parity_case.raw_count),
           label + " raw ids: " +
               first_divergence(raw, parity_case.raw, parity_case.raw_count));
    expect(same_ids(sdxl.l.ids, parity_case.l, parity_case.l_count),
           label + " CLIP-L chunks: " +
               first_divergence(sdxl.l.ids, parity_case.l,
                                parity_case.l_count));
    expect(same_ids(sdxl.g.ids, parity_case.g, parity_case.g_count),
           label + " CLIP-G chunks: " +
               first_divergence(sdxl.g.ids, parity_case.g,
                                parity_case.g_count));
    expect(sdxl.l.valid_tokens == parity_case.l_num_tokens,
           label + " CLIP-L valid_tokens " +
               std::to_string(sdxl.l.valid_tokens) +
               " != reference num_tokens " +
               std::to_string(parity_case.l_num_tokens));
    expect(sdxl.g.valid_tokens == parity_case.g_num_tokens,
           label + " CLIP-G valid_tokens " +
               std::to_string(sdxl.g.valid_tokens) +
               " != reference num_tokens " +
               std::to_string(parity_case.g_num_tokens));
  }
  std::cout << "clip parity cases: " << checked << " (" << divergences
            << " documented divergence" << (divergences == 1 ? "" : "s")
            << "), failures: " << failures << "\n";

  if (failures != 0) {
    std::cerr << failures << " failure(s)\n";
    return 1;
  }
  std::cout << "all clip tokenizer tests passed\n";
  return 0;
}
