// Native Qwen BPE tokenizer tests.
//
// Two layers:
//   1. Checkpoint-free unit tests: UTF-8 codec strictness and NFC vectors
//      (expected outputs generated from CPython unicodedata).
//   2. Oracle-parity regression gate: embedded fixtures generated by
//      tools/export_tokenizer_parity_fixtures.py from the transformers
//      Qwen2TokenizerFast oracle on the MiniMax-H3 processor directory,
//      plus the recorded golden-prompt gate (439 tokens).
// Layer 2 needs the real checkpoint tokenizer files; when they are absent
// the test reports SKIP via exit code 77 (registered SKIP_RETURN_CODE).

#include "dif/support/error.hpp"
#include "dif/text/qwen_bpe_tokenizer.hpp"
#include "dif/text/unicode.hpp"

#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

#include "tokenizer_parity_fixtures.inc"

namespace {

int failures = 0;

void expect(bool condition, const std::string &message) {
  if (!condition) {
    ++failures;
    std::cerr << "FAIL: " << message << "\n";
  }
}

std::string nfc_utf8(const std::string &input) {
  const auto cps = dif::text::unicode::decode_utf8(input);
  const auto norm = dif::text::unicode::nfc(cps);
  std::string out;
  for (const char32_t cp : norm)
    dif::text::unicode::append_utf8(out, cp);
  return out;
}

void run_unit_tests() {
  using dif::text::unicode::decode_utf8;

  // UTF-8 round trip incl. astral plane.
  {
    const std::string sample = "aé你\U0001f600";
    const auto cps = decode_utf8(sample);
    expect(cps.size() == 4U, "utf8 decode count");
    std::string round;
    for (const char32_t cp : cps)
      dif::text::unicode::append_utf8(round, cp);
    expect(round == sample, "utf8 round trip");
  }
  // Strict decoder rejections.
  for (const std::string bad :
       {std::string("\xff"), std::string("\xc0\xaf"),
        std::string("\xed\xa0\x80"), std::string("\xf0\x28\x8c\x28"),
        std::string("\xe4\xbd")}) {
    bool threw = false;
    try {
      decode_utf8(bad);
    } catch (const dif::Error &) {
      threw = true;
    }
    expect(threw, "utf8 strictness rejects malformed input");
  }
  // Property classes (the measured Oniguruma semantics).
  using dif::text::unicode::is_letter;
  using dif::text::unicode::is_number;
  using dif::text::unicode::is_whitespace;
  expect(is_letter(U'a') && is_letter(U'é') && is_letter(U'你') &&
             is_letter(0x1D573),
         "\\p{L} membership");
  expect(!is_letter(U'1') && !is_letter(U' ') && !is_letter(U'!'),
         "\\p{L} exclusion");
  expect(is_number(U'7') && is_number(U'١') && is_number(0x216B) &&
             is_number(0x2460),
         "\\p{N} membership");
  expect(is_whitespace(U' ') && is_whitespace(U'\t') &&
             is_whitespace(0x00A0) && is_whitespace(0x3000) &&
             is_whitespace(0x0085) && is_whitespace(0x2028),
         "\\s includes Unicode White_Space");
  expect(!is_whitespace(0x001C) && !is_whitespace(0x200B) &&
             !is_whitespace(0x00AD) && !is_whitespace(0x180E),
         "\\s excludes non-White_Space controls/format chars");
  // NFC vectors (expected generated from CPython unicodedata NFC).
  for (const auto &nfc_case : fixtures::kNfcCases) {
    const std::string got = nfc_utf8(nfc_case.input);
    expect(got == nfc_case.expected,
           std::string("nfc vector mismatch for input ") + nfc_case.input);
  }
}

std::string read_file(const std::filesystem::path &path) {
  std::ifstream in(path, std::ios::binary);
  std::ostringstream buffer;
  buffer << in.rdbuf();
  return std::move(buffer).str();
}

std::string first_divergence(const std::vector<std::int32_t> &got,
                             const std::int32_t *want, std::size_t want_count) {
  std::size_t i = 0;
  while (i < got.size() && i < want_count && got[i] == want[i])
    ++i;
  std::ostringstream out;
  out << "got " << got.size() << " ids, want " << want_count
      << ", first divergence at " << i << " (got ";
  if (i < got.size())
    out << got[i];
  else
    out << "<end>";
  out << ", want ";
  if (i < want_count)
    out << want[i];
  else
    out << "<end>";
  out << ")";
  return out.str();
}

} // namespace

int main() {
  run_unit_tests();

  const char *processor_env = std::getenv("DIF_H3_PROCESSOR");
  const std::filesystem::path processor =
      processor_env != nullptr
          ? std::filesystem::path(processor_env)
          : std::filesystem::path(
                "/home/alex/.serenity/models/checkpoints/MiniMax-H3/FL2VA/"
                "processor");
  const std::filesystem::path tokenizer_json = processor / "tokenizer.json";
  const std::filesystem::path tokenizer_config =
      processor / "tokenizer_config.json";

  if (!std::filesystem::exists(tokenizer_json) ||
      !std::filesystem::exists(tokenizer_config)) {
    if (failures != 0)
      return 1;
    std::cout << "SKIP: checkpoint tokenizer files not found under "
              << processor << "\n";
    return 77;
  }

  const auto tokenizer =
      dif::text::QwenBpeTokenizer::load(tokenizer_json, tokenizer_config);
  expect(tokenizer.id_space() == fixtures::kExpectedIdSpace,
         "id space must match transformers (vocab + 26 json added + 7 "
         "config-only added)");
  expect(tokenizer.added_tokens().size() == fixtures::kExpectedAddedTokens,
         "added-token count must match transformers added_tokens_decoder");

  std::size_t parity_failures = 0;
  for (const auto &parity_case : fixtures::kParityCases) {
    const auto got = tokenizer.encode(parity_case.utf8);
    bool ok = got.size() == parity_case.id_count;
    for (std::size_t i = 0; ok && i < got.size(); ++i)
      ok = got[i] == parity_case.ids[i];
    if (!ok) {
      ++parity_failures;
      expect(false, std::string("parity case '") + parity_case.name + "': " +
                        first_divergence(got, parity_case.ids,
                                         parity_case.id_count));
    }
  }
  std::cout << "parity cases: "
            << (sizeof(fixtures::kParityCases) /
                sizeof(fixtures::kParityCases[0]))
            << ", mismatches: " << parity_failures << "\n";

  // Golden artifact gate (the recorded 439-token prompt), when present.
  const std::filesystem::path golden =
      "/home/alex/diffusion-compiler/artifacts/"
      "h3-quality-natural-language-2026-08-30/prompt.txt";
  if (std::filesystem::exists(golden)) {
    std::string raw = read_file(golden);
    std::string stripped = raw;
    while (!stripped.empty() && stripped.back() == '\n')
      stripped.pop_back();
    const auto ids_stripped = tokenizer.encode(stripped);
    const auto ids_raw = tokenizer.encode(raw);
    expect(ids_stripped.size() == fixtures::kGoldenStrippedCount,
           "golden stripped prompt token count (439)");
    expect(!ids_stripped.empty() &&
               ids_stripped.back() == fixtures::kGoldenStrippedLastId,
           "golden stripped prompt last id");
    expect(ids_raw.size() == fixtures::kGoldenRawCount,
           "golden raw prompt token count (439)");
    expect(!ids_raw.empty() && ids_raw.back() == fixtures::kGoldenRawLastId,
           "golden raw prompt last id");
  } else {
    std::cout << "note: golden artifact prompt not found; embedded "
                 "golden_prompt_* fixtures still cover the content\n";
  }

  if (failures != 0) {
    std::cerr << failures << " failure(s)\n";
    return 1;
  }
  std::cout << "all tokenizer tests passed\n";
  return 0;
}
