// Physical concatenation along one axis: the if-chain over inputs is
// generated by the emitter.
extern "C" __global__ void ${function}(${parameters}) {
  unsigned long long i = (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x;
  if (i < ${count}ULL) {
    unsigned long long inner_index = i % ${inner}ULL,
                       axis_coordinate = (i / ${inner}ULL) % ${axis_extent}ULL,
                       outer = i / (${axis_extent}ULL * ${inner}ULL), source = 0ULL;
${selection}
  }
}
