// Split each selected row of values [T, C*H] into C outputs [S, H]; the
// per-chunk stores are generated by the emitter.
extern "C" __global__ void ${function}(const dif_scalar* values, const int* indices${outputs}) {
  unsigned long long i = (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x;
  if (i < ${count}ULL) {
    unsigned long long row = i / ${width}ULL, col = i % ${width}ULL;
    int source = indices[row];
${chunks}
  }
}
