#!/usr/bin/env python3
"""Dev-time generator for src/text/unicode_tables.inc.

Python is a development tool here (the shipped binary is pure C++); the
generated .inc is committed. Data source: CPython's unicodedata (Unicode
15.0 on Python 3.12), matching the Unicode version of the vendored
Oniguruma tables that HF `tokenizers` uses for \\p{L}/\\p{N}/\\s.

Emits:
  - kLetterRanges / kNumberRanges: \\p{L} and \\p{N} codepoint ranges
  - kWhitespace: Oniguruma UTF-8 \\s = the Unicode White_Space set
    (measured against the HF pre-tokenizer: U+00A0 IS \\s, U+001C-1F are NOT)
  - NFC data: full canonical decompositions (NFD, Hangul excluded),
    combining classes, primary composition pairs (exclusions filtered by
    NFC round-trip)
"""
import sys, unicodedata

MAX = 0x110000
out_path = sys.argv[1] if len(sys.argv) > 1 else "src/text/unicode_tables.inc"

def ranges(pred):
    out = []
    start = None
    for cp in range(MAX):
        v = False if 0xD800 <= cp <= 0xDFFF else pred(cp)
        if v and start is None:
            start = cp
        elif not v and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX - 1))
    return out

letters = ranges(lambda cp: unicodedata.category(chr(cp))[0] == 'L')
numbers = ranges(lambda cp: unicodedata.category(chr(cp))[0] == 'N')
# Unicode White_Space property (stable since 6.3).
ws = ([0x0009, 0x000A, 0x000B, 0x000C, 0x000D, 0x0020, 0x0085, 0x00A0, 0x1680]
      + list(range(0x2000, 0x200B)) + [0x2028, 0x2029, 0x202F, 0x205F, 0x3000])

decomp = {}
for cp in range(MAX):
    if 0xAC00 <= cp <= 0xD7A3 or 0xD800 <= cp <= 0xDFFF:
        continue
    ch = chr(cp)
    d = unicodedata.normalize('NFD', ch)
    if d != ch:
        decomp[cp] = [ord(c) for c in d]

ccc = {}
for cp in range(MAX):
    if 0xD800 <= cp <= 0xDFFF:
        continue
    c = unicodedata.combining(chr(cp))
    if c:
        ccc[cp] = c

comp = []
for cp in range(MAX):
    if 0xAC00 <= cp <= 0xD7A3 or 0xD800 <= cp <= 0xDFFF:
        continue
    ch = chr(cp)
    dec = unicodedata.decomposition(ch)
    if not dec or dec.startswith('<'):
        continue
    parts = dec.split()
    if len(parts) != 2:
        continue
    a, b = int(parts[0], 16), int(parts[1], 16)
    if unicodedata.normalize('NFC', chr(a) + chr(b)) == ch:
        comp.append(((a << 21) | b, cp))
comp.sort()

pool = []
dentries = []
for cp in sorted(decomp):
    seq = decomp[cp]
    dentries.append((cp, len(pool), len(seq)))
    pool.extend(seq)

with open(out_path, 'w') as f:
    w = f.write
    w("// GENERATED by scripts/gen_unicode_tables.py — do not edit by hand.\n")
    w("// Unicode version: %s (CPython unicodedata).\n" % unicodedata.unidata_version)
    w("// clang-format off\n")
    w("namespace tables {\n\n")
    w("struct Range { char32_t lo; char32_t hi; };\n")
    w("struct Decomp { char32_t cp; std::uint32_t off; std::uint32_t len; };\n")
    w("struct Ccc { char32_t cp; std::uint8_t ccc; };\n")
    w("struct Comp { std::uint64_t key; char32_t out; };\n\n")

    def emit_ranges(name, rr):
        w("inline constexpr Range %s[] = {\n" % name)
        for i in range(0, len(rr), 6):
            w("    " + " ".join("{0x%X,0x%X}," % r for r in rr[i:i+6]) + "\n")
        w("};\n\n")

    emit_ranges("kLetterRanges", letters)
    emit_ranges("kNumberRanges", numbers)
    w("inline constexpr char32_t kWhitespace[] = {\n    "
      + ", ".join("0x%X" % c for c in ws) + "\n};\n\n")

    w("inline constexpr char32_t kDecompPool[] = {\n")
    for i in range(0, len(pool), 10):
        w("    " + " ".join("0x%X," % c for c in pool[i:i+10]) + "\n")
    w("};\n\n")
    w("inline constexpr Decomp kDecomp[] = {\n")
    for i in range(0, len(dentries), 4):
        w("    " + " ".join("{0x%X,%d,%d}," % d for d in dentries[i:i+4]) + "\n")
    w("};\n\n")
    w("inline constexpr Ccc kCcc[] = {\n")
    items = sorted(ccc.items())
    for i in range(0, len(items), 6):
        w("    " + " ".join("{0x%X,%d}," % it for it in items[i:i+6]) + "\n")
    w("};\n\n")
    w("inline constexpr Comp kComp[] = {\n")
    for i in range(0, len(comp), 4):
        w("    " + " ".join("{0x%XULL,0x%X}," % c for c in comp[i:i+4]) + "\n")
    w("};\n\n")
    w("} // namespace tables\n")
    w("// clang-format on\n")

print("letters:%d numbers:%d ws:%d decomp:%d pool:%d ccc:%d comp:%d -> %s" %
      (len(letters), len(numbers), len(ws), len(dentries), len(pool),
       len(ccc), len(comp), out_path))
