#!/usr/bin/env python3
"""Creator oracle for the SDXL discrete sigma schedule.

Records the reference sampler's own ModelSamplingDiscrete tables and normal
scheduler as C++ initializers. Every float is written as a hexadecimal
literal so the fixture round-trips through float32 exactly.

usage: export_sdxl_schedule_reference.py --reference-source CHECKOUT
           --output tests/sdxl_schedule_fixtures.inc [--steps 1 2 4 ...]
"""

from __future__ import annotations

import argparse
import math
import subprocess
import sys
from pathlib import Path


def literal(value: float) -> str:
    """Shortest hexadecimal float literal that round-trips exactly."""
    value = float(value)
    if value == 0.0:
        return "0.0F" if math.copysign(1.0, value) > 0.0 else "-0.0F"
    text = value.hex()
    mantissa, _, exponent = text.partition("p")
    whole, _, fraction = mantissa.partition(".")
    fraction = fraction.rstrip("0")
    mantissa = f"{whole}.{fraction}" if fraction else whole
    return f"{mantissa}p{exponent}F"


def block(name: str, values, per_line: int = 4) -> list[str]:
    lines = [f"inline constexpr float {name}[{len(values)}] = {{"]
    for start in range(0, len(values), per_line):
        row = ", ".join(literal(v) for v in values[start:start + per_line])
        lines.append(f"    {row},")
    lines.append("};")
    return lines


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reference-source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--steps", type=int, nargs="+",
                        default=[1, 2, 4, 10, 20, 25, 30, 50, 100])
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    if args.output.exists() and not args.force:
        raise SystemExit(f"refusing to overwrite {args.output}")
    source = args.reference_source.resolve()
    if not (source / "comfy").is_dir():
        raise SystemExit(f"{source} is not the reference sampler checkout")
    sys.path.insert(0, str(source))
    commit = subprocess.check_output(
        ["git", "-C", str(source), "rev-parse", "HEAD"], text=True).strip()

    import torch
    import comfy.model_sampling as model_sampling
    import comfy.samplers as samplers

    sampling = model_sampling.ModelSamplingDiscrete()
    sigmas = [float(v) for v in sampling.sigmas]
    log_sigmas = [float(v) for v in sampling.log_sigmas]

    def sigma_at(t: float) -> float:
        return float(sampling.sigma(torch.tensor(t, dtype=torch.float32)))

    def log_sigma_at(t: float) -> float:
        # The interpolant behind sigma(): reproduced from the reference's own
        # tables so the exponential can be gated separately.
        clamped = min(max(t, 0.0), float(len(sigmas) - 1))
        low, high = math.floor(clamped), math.ceil(clamped)
        w = torch.tensor(clamped, dtype=torch.float32).frac()
        return float((1 - w) * sampling.log_sigmas[low] + w * sampling.log_sigmas[high])

    def timestep_for(sigma: float) -> int:
        return int(sampling.timestep(torch.tensor(sigma, dtype=torch.float32)))

    def divisor(sigma: float) -> float:
        return float((torch.tensor(sigma, dtype=torch.float32) ** 2 + 1.0) ** 0.5)

    def f32(value: float) -> float:
        return float(torch.tensor(value, dtype=torch.float32))

    spot_timesteps = [f32(v) for v in
                      [0.0, 0.5, 1.0, 1.5, 2.25, 10.75, 123.25, 250.5, 333.333,
                       499.5, 500.5, 512.0, 666.666, 750.875, 900.0, 998.75,
                       999.0, 1000.0, 1234.5, -5.0]]
    spot_sigmas = [f32(v) for v in
                   [sigmas[0], sigmas[1], sigmas[250], sigmas[500],
                    sigmas[750], sigmas[999],
                    (sigmas[0] + sigmas[1]) / 2.0,
                    (sigmas[7] + sigmas[8]) / 2.0,
                    (sigmas[100] + sigmas[101]) / 2.0,
                    (sigmas[400] + sigmas[401]) / 2.0,
                    (sigmas[512] + sigmas[513]) / 2.0,
                    (sigmas[998] + sigmas[999]) / 2.0,
                    0.03, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 14.0]]

    lines = [
        "// Generated by tools/export_sdxl_schedule_reference.py; do not edit.",
        f"// Reference sampler commit: {commit}",
        f"// torch {torch.__version__}, cpu capability "
        f"{torch.backends.cpu.get_cpu_capability()}",
        "// ModelSamplingDiscrete defaults: linear betas, linear_start 0.00085,",
        "// linear_end 0.012, 1000 timesteps (SDXL).",
        "",
        "namespace sdxl_schedule_fixtures {",
        "",
        f"inline constexpr unsigned kTimesteps = {len(sigmas)}U;",
    ]
    lines += block("kSigmas", sigmas)
    lines += block("kLogSigmas", log_sigmas)
    lines += [
        "",
        f"inline constexpr float kSigmaMin = {literal(float(sampling.sigma_min))};",
        f"inline constexpr float kSigmaMax = {literal(float(sampling.sigma_max))};",
        "",
        "struct SigmaAtCase {",
        "  float timestep;",
        "  float log_sigma;",
        "  float sigma;",
        "};",
        f"inline constexpr SigmaAtCase kSigmaAtCases[{len(spot_timesteps)}] = {{",
    ]
    for t in spot_timesteps:
        lines.append(f"    {{{literal(t)}, {literal(log_sigma_at(t))}, "
                     f"{literal(sigma_at(t))}}},")
    lines += [
        "};",
        "",
        "struct TimestepForCase {",
        "  float sigma;",
        "  unsigned timestep;",
        "};",
        f"inline constexpr TimestepForCase kTimestepForCases[{len(spot_sigmas)}] = {{",
    ]
    for s in spot_sigmas:
        lines.append(f"    {{{literal(s)}, {timestep_for(s)}U}},")
    lines += [
        "};",
        "",
        "struct ScheduleCase {",
        "  unsigned steps;",
        "  unsigned start_timestep;",
        "  unsigned end_timestep;",
        "  bool max_denoise;",
        "  unsigned sigma_count;  // steps + 1 (terminal zero appended)",
        "  const float *timesteps;  // steps entries",
        "  const float *log_sigmas;  // steps entries",
        "  const float *sigmas;  // sigma_count entries",
        "  const float *unet_timesteps;  // steps entries",
        "  const float *input_divisors;  // steps entries",
        "};",
    ]
    cases = []
    maximum = float(sampling.sigma_max)
    start_timestep = timestep_for(maximum)
    end_timestep = timestep_for(float(sampling.sigma_min))
    for steps in args.steps:
        schedule = [float(v) for v in samplers.normal_scheduler(sampling, steps)]
        grid = [float(v) for v in torch.linspace(
            torch.tensor(start_timestep), torch.tensor(end_timestep), steps)]
        denoise_fully = (math.isclose(maximum, schedule[0], rel_tol=1e-05)
                         or schedule[0] > maximum)
        lines += block(f"kSchedule{steps}Timesteps", grid)
        lines += block(f"kSchedule{steps}LogSigmas",
                       [log_sigma_at(t) for t in grid])
        lines += block(f"kSchedule{steps}Sigmas", schedule)
        lines += block(f"kSchedule{steps}UnetTimesteps",
                       [float(timestep_for(s)) for s in schedule[:-1]])
        lines += block(f"kSchedule{steps}InputDivisors",
                       [divisor(s) for s in schedule[:-1]])
        cases.append(
            f"    {{{steps}U, {start_timestep}U, {end_timestep}U, "
            f"{'true' if denoise_fully else 'false'}, {len(schedule)}U,\n"
            f"     kSchedule{steps}Timesteps, kSchedule{steps}LogSigmas, "
            f"kSchedule{steps}Sigmas,\n"
            f"     kSchedule{steps}UnetTimesteps, "
            f"kSchedule{steps}InputDivisors}},")
    lines.append(f"inline constexpr ScheduleCase kScheduleCases[{len(cases)}] = {{")
    lines += cases
    lines += ["};", "", "} // namespace sdxl_schedule_fixtures", ""]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines))
    print(f"wrote {args.output}: {len(sigmas)} table rows, {len(cases)} schedules, "
          f"reference {commit[:12]}")


if __name__ == "__main__":
    main()
