# Embed src/compiler/kernels/*.cu as string literals.
#
# Invoked at build time (add_custom_command in CMakeLists.txt):
#   cmake -DKERNEL_DIR=<dir> -DOUTPUT=<file.cpp> -P cmake/embed_kernels.cmake
#
# Emits `embedded_kernel_templates()` for src/compiler/kernel_template.cpp:
# a name -> text table where the name is the file stem. Each file becomes one
# raw string literal; a file containing the delimiter sequence fails the build
# rather than producing a broken literal.
if(NOT DEFINED KERNEL_DIR OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "embed_kernels.cmake needs -DKERNEL_DIR and -DOUTPUT")
endif()

file(GLOB kernel_files "${KERNEL_DIR}/*.cu")
list(SORT kernel_files)

set(delimiter "DIFKERNEL")
set(content "// Generated by cmake/embed_kernels.cmake from src/compiler/kernels/*.cu.\n")
string(APPEND content "// Do not edit; edit the .cu files.\n")
string(APPEND content "#include <string_view>\n#include <unordered_map>\n\n")
string(APPEND content "namespace dif::compiler {\n\n")
string(APPEND content "const std::unordered_map<std::string_view, std::string_view> &\n")
string(APPEND content "embedded_kernel_templates() {\n")
string(APPEND content "  static const std::unordered_map<std::string_view, std::string_view> table = {\n")
foreach(path IN LISTS kernel_files)
  get_filename_component(stem "${path}" NAME_WE)
  file(READ "${path}" text)
  # A placeholder inside a comment line would be substituted like any other
  # (the engine cannot tell prose from code) and could smuggle a multi-line
  # fragment out of the comment; refuse it at embed time.
  string(REGEX MATCH "(^|\n)[ \t]*//[^\n]*\\$\\{" comment_placeholder "${text}")
  if(NOT comment_placeholder STREQUAL "")
    message(FATAL_ERROR "${path}: a placeholder inside a // comment line is not allowed")
  endif()
  string(FIND "${text}" ")${delimiter}\"" clash)
  if(NOT clash EQUAL -1)
    message(FATAL_ERROR "${path} contains the raw-string delimiter )${delimiter}\"")
  endif()
  string(APPEND content "      {\"${stem}\", R\"${delimiter}(${text})${delimiter}\"},\n")
endforeach()
string(APPEND content "  };\n  return table;\n}\n\n} // namespace dif::compiler\n")

# Only rewrite when changed so dependents do not rebuild needlessly.
set(existing "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" existing)
endif()
if(NOT existing STREQUAL content)
  file(WRITE "${OUTPUT}" "${content}")
endif()
